#ifndef _BSP_IRQ_DRIVER_H_
#define _BSP_IRQ_DRIVER_H_

/* Exception */
#define MemManage_Handler_IRQ_Num           ((IRQn_t) -7)
#define BusFault_Handler_IRQ_Num            ((IRQn_t) -6)
#define UsageFault_Handler_IRQ_Num          ((IRQn_t) -5)
#define SVC_Handler_IRQ_Num                 ((IRQn_t) -4)
#define DebugMon_Handler_IRQ_Num            ((IRQn_t) -3)
#define PendSV_Handler_IRQ_Num              ((IRQn_t) -2)
#define SysTick_Handler_IRQ_Num             ((IRQn_t) -1)

#define BSP_EXCEPTION_OFFSET                (7)

/* Interrupt */
#define WWDG_IRQHandler_IRQ_Num             ((IRQn_t) 0)
#define PVD_IRQHandler_IRQ_Num              ((IRQn_t) 1)
#define TAMPER_IRQHandler_IRQ_Num           ((IRQn_t) 2)
#define RTC_IRQHandler_IRQ_Num              ((IRQn_t) 3)
#define FLASH_IRQHandler_IRQ_Num            ((IRQn_t) 4)
#define RCC_IRQHandler_IRQ_Num              ((IRQn_t) 5)
#define EXTI0_IRQHandler_IRQ_Num            ((IRQn_t) 6)
#define EXTI1_IRQHandler_IRQ_Num            ((IRQn_t) 7)
#define EXTI2_IRQHandler_IRQ_Num            ((IRQn_t) 8)
#define EXTI3_IRQHandler_IRQ_Num            ((IRQn_t) 9)
#define EXTI4_IRQHandler_IRQ_Num            ((IRQn_t) 10)
#define DMA1_Channel1_IRQHandler_IRQ_Num    ((IRQn_t) 11)
#define DMA1_Channel2_IRQHandler_IRQ_Num    ((IRQn_t) 12)
#define DMA1_Channel3_IRQHandler_IRQ_Num    ((IRQn_t) 13)
#define DMA1_Channel4_IRQHandler_IRQ_Num    ((IRQn_t) 14)
#define DMA1_Channel5_IRQHandler_IRQ_Num    ((IRQn_t) 15)
#define DMA1_Channel6_IRQHandler_IRQ_Num    ((IRQn_t) 16)
#define DMA1_Channel7_IRQHandler_IRQ_Num    ((IRQn_t) 17)
#define ADC1_2_IRQHandler_IRQ_Num           ((IRQn_t) 18)
#define USB_HP_CAN_TX_IRQHandler_IRQ_Num    ((IRQn_t) 19)
#define USB_LP_CAN_RX0_IRQHandler_IRQ_Num   ((IRQn_t) 20)
#define CAN_RX1_IRQHandler_IRQ_Num          ((IRQn_t) 21)
#define CAN_SCE_IRQHandler_IRQ_Num          ((IRQn_t) 22)
#define EXTI9_5_IRQHandler_IRQ_Num          ((IRQn_t) 23)
#define TIM1_BRK_IRQHandler_IRQ_Num         ((IRQn_t) 24)
#define TIM1_UP_IRQHandler_IRQ_Num          ((IRQn_t) 25)
#define TIM1_TRG_COM_IRQHandler_IRQ_Num     ((IRQn_t) 26)
#define TIM1_CC_IRQHandler_IRQ_Num          ((IRQn_t) 27)
#define TIM2_IRQHandler_IRQ_Num             ((IRQn_t) 28)
#define TIM3_IRQHandler_IRQ_Num             ((IRQn_t) 29)
#define TIM4_IRQHandler_IRQ_Num             ((IRQn_t) 30)
#define I2C1_EV_IRQHandler_IRQ_Num          ((IRQn_t) 31)
#define I2C1_ER_IRQHandler_IRQ_Num          ((IRQn_t) 32)
#define I2C2_EV_IRQHandler_IRQ_Num          ((IRQn_t) 33)
#define I2C2_ER_IRQHandler_IRQ_Num          ((IRQn_t) 34)
#define SPI1_IRQHandler_IRQ_Num             ((IRQn_t) 35)
#define SPI2_IRQHandler_IRQ_Num             ((IRQn_t) 36)
#define USART1_IRQHandler_IRQ_Num           ((IRQn_t) 37)
#define USART2_IRQHandler_IRQ_Num           ((IRQn_t) 38)
#define USART3_IRQHandler_IRQ_Num           ((IRQn_t) 39)
#define EXTI15_10_IRQHandler_IRQ_Num        ((IRQn_t) 40)
#define RTCAlarm_IRQHandler_IRQ_Num         ((IRQn_t) 41)
#define USBWakeup_IRQHandler_IRQ_Num        ((IRQn_t) 42)
#define TIM8_BRK_IRQHandler_IRQ_Num         ((IRQn_t) 43)
#define TIM8_UP_IRQHandler_IRQ_Num          ((IRQn_t) 44)
#define TIM8_TRG_COM_IRQHandler_IRQ_Num     ((IRQn_t) 45)
#define TIM8_CC_IRQHandler_IRQ_Num          ((IRQn_t) 46)
#define ADC3_IRQHandler_IRQ_Num             ((IRQn_t) 47)
#define FSMC_IRQHandler_IRQ_Num             ((IRQn_t) 48)
#define SDIO_IRQHandler_IRQ_Num             ((IRQn_t) 49)
#define TIM5_IRQHandler_IRQ_Num             ((IRQn_t) 50)
#define SPI3_IRQHandler_IRQ_Num             ((IRQn_t) 51)
#define UART4_IRQHandler_IRQ_Num            ((IRQn_t) 52)
#define UART5_IRQHandler_IRQ_Num            ((IRQn_t) 53)
#define TIM6_IRQHandler_IRQ_Num             ((IRQn_t) 54)
#define TIM7_IRQHandler_IRQ_Num             ((IRQn_t) 55)
#define DMA2_Channel1_IRQHandler_IRQ_Num    ((IRQn_t) 56)
#define DMA2_Channel2_IRQHandler_IRQ_Num    ((IRQn_t) 57)
#define DMA2_Channel3_IRQHandler_IRQ_Num    ((IRQn_t) 58)
#define DMA2_Channel4_5_IRQHandler_IRQ_Num  ((IRQn_t) 59)

#define BSP_TOTAL_IRQ                       (60U)

#endif
