#ifndef _BSP_MCU_STANDBY_DRIVER_H_
#define _BSP_MCU_STANDBY_DRIVER_H_

#include "stm32f1xxx.h"

#define BSP_MODULE_STANDBY_REG_TYPE_SHIFT (8U)

#define BSP_MODULE_STANDBY_AHB_REG_MODULE (0x00 << BSP_MODULE_STANDBY_REG_TYPE_SHIFT)
#define BSP_MODULE_STANDBY_APB2_REG_MODULE (0x01 << BSP_MODULE_STANDBY_REG_TYPE_SHIFT)
#define BSP_MODULE_STANDBY_APB1_REG_MODULE (0x02 << BSP_MODULE_STANDBY_REG_TYPE_SHIFT)

/**
 * @brief Peripherals in MCU
 */
typedef enum e_bsp_module_standby
{
    BSP_MODULE_STANDBY_ALTERNATIVE_FUNCTION_IO,
    BSP_MODULE_STANDBY_IO_PORT_A,
    BSP_MODULE_STANDBY_IO_PORT_B,
    BSP_MODULE_STANDBY_IO_PORT_C,
    BSP_MODULE_STANDBY_ADC_1,
    BSP_MODULE_STANDBY_ADC_2,
    BSP_MODULE_STANDBY_TIM_1,
    BSP_MODULE_STANDBY_SPI_1,
    BSP_MODULE_STANDBY_USART_1,
    BSP_MODULE_STANDBY_TIM_2,
    BSP_MODULE_STANDBY_TIM_3,
    BSP_MODULE_STANDBY_TIM_4,
    BSP_MODULE_STANDBY_TIM_5,
    BSP_MODULE_STANDBY_WDT,
    BSP_MODULE_STANDBY_SPI_2,
    BSP_MODULE_STANDBY_SPI_3,
    BSP_MODULE_STANDBY_USART_2,
    BSP_MODULE_STANDBY_USART_3,
    BSP_MODULE_STANDBY_USART_4,
    BSP_MODULE_STANDBY_USART_5,
    BSP_MODULE_STANDBY_I2C_1,
    BSP_MODULE_STANDBY_I2C_2,
    BSP_MODULE_STANDBY_CAN_1,
    BSP_MODULE_STANDBY_CAN_2,
    BSP_MODULE_STANDBY_BACKUP_INTERFACE,
    BSP_MODULE_STANDBY_POWER_INTERFACE,
    BSP_MODULE_STANDBY_DMAC_1,
    BSP_MODULE_STANDBY_DMAC_2,
    BSP_MODULE_STANDBY_SRAM,
    BSP_MODULE_STANDBY_FLITF,
    BSP_MODULE_STANDBY_CRC,
    BSP_MODULE_STANDBY_TOTAL
} bsp_module_standby_t;


/**
 * @brief Struct contains infor of module standby
 */
typedef struct st_bsp_standby_config
{
    volatile uint32_t *msr_reg;
    uint32_t mask_value;
} bsp_standby_config_t;

extern const bsp_standby_config_t g_bsp_module_standby_configs[BSP_MODULE_STANDBY_TOTAL];

#endif
