#ifndef _BSP_IO_DRIVER_H_
#define _BSP_IO_DRIVER_H_

#include "bsp_common.h"

#define BSP_IO_PORT_TYPE_SHIFT (8U)

/**
 * @brief Specific Pin for device
 */
typedef enum e_bsp_io
{
    BSP_IO_PORTA_PIN_0 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 0U,
    BSP_IO_PORTA_PIN_1 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 1U,
    BSP_IO_PORTA_PIN_2 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 2U,
    BSP_IO_PORTA_PIN_3 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 3U,
    BSP_IO_PORTA_PIN_4 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 4U,
    BSP_IO_PORTA_PIN_5 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 5U,
    BSP_IO_PORTA_PIN_6 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 6U,
    BSP_IO_PORTA_PIN_7 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 7U,
    BSP_IO_PORTA_PIN_8 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 8U,
    BSP_IO_PORTA_PIN_9 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 9U,
    BSP_IO_PORTA_PIN_10 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 10U,
    BSP_IO_PORTA_PIN_11 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 11U,
    BSP_IO_PORTA_PIN_12 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 12U,
    BSP_IO_PORTA_PIN_13 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 13U,
    BSP_IO_PORTA_PIN_14 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 14U,
    BSP_IO_PORTA_PIN_15 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 15U,

    BSP_IO_PORTB_PIN_0 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 0U,
    BSP_IO_PORTB_PIN_1 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 1U,
    BSP_IO_PORTB_PIN_2 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 2U,
    BSP_IO_PORTB_PIN_3 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 3U,
    BSP_IO_PORTB_PIN_4 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 4U,
    BSP_IO_PORTB_PIN_5 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 5U,
    BSP_IO_PORTB_PIN_6 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 6U,
    BSP_IO_PORTB_PIN_7 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 7U,
    BSP_IO_PORTB_PIN_8 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 8U,
    BSP_IO_PORTB_PIN_9 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 9U,
    BSP_IO_PORTB_PIN_10 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 10U,
    BSP_IO_PORTB_PIN_11 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 11U,
    BSP_IO_PORTB_PIN_12 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 12U,
    BSP_IO_PORTB_PIN_13 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 13U,
    BSP_IO_PORTB_PIN_14 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 14U,
    BSP_IO_PORTB_PIN_15 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 15U,

    BSP_IO_PORTC_PIN_13 = (2U << BSP_IO_PORT_TYPE_SHIFT) | 13U,
    BSP_IO_PORTC_PIN_14 = (2U << BSP_IO_PORT_TYPE_SHIFT) | 14U,
    BSP_IO_PORTC_PIN_15 = (2U << BSP_IO_PORT_TYPE_SHIFT) | 15U,
} bsp_io_t;

#endif