#ifndef _BSP_IO_DRIVER_H_
#define _BSP_IO_DRIVER_H_

#include "bsp_common.h"

#define BSP_IO_PORT_TYPE_SHIFT (8U)

/**
 * @brief Specific Pin for device.
 */
typedef enum e_bsp_io
{                                                             ///< Comment: Default - Remapping
    BSP_IO_PORTA_PIN_0 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 0U, ///< WKUP/USART2_CTS/ADC12_IN0/TIM2_CH1_ETR
    BSP_IO_PORTA_PIN_1 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 1U, ///< USART2_RTS/ADC12_IN1/TIM2_CH2
    BSP_IO_PORTA_PIN_2 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 2U, ///< USART2_TX/ADC12_IN2/TIM2_CH3
    BSP_IO_PORTA_PIN_3 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 3U, ///< USART2_RX/ADC12_IN3/TIM2_CH4
    BSP_IO_PORTA_PIN_4 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 4U, ///< SPI1_NSS/USART2_CK/ADC12_IN4
    BSP_IO_PORTA_PIN_5 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 5U, ///< SPI1_SCK/ADC12_IN5
    BSP_IO_PORTA_PIN_6 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 6U, ///< SPI1_MISO/ADC12_IN6/TIM3_CH1 - TIM1_BKIN
    BSP_IO_PORTA_PIN_7 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 7U, ///< SPI1_MOSI/ADC12_IN7/TIM3_CH2 - TIM1_CH1N
    BSP_IO_PORTA_PIN_8 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 8U, ///< USART1_CK/TIM1_CH1/MCO
    BSP_IO_PORTA_PIN_9 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 9U, ///< USART1_TX/TIM1_CH2
    BSP_IO_PORTA_PIN_10 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 10U, ///< USART1_RX/TIM1_CH3
    BSP_IO_PORTA_PIN_11 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 11U, ///< USART1_CTS/CANRX/USBDM/TIM1_CH4
    BSP_IO_PORTA_PIN_12 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 12U, ///< USART1_RTS/CANTX/USBDP/TIM1_ETR
    BSP_IO_PORTA_PIN_13 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 13U, ///< JTMS/SWDIO - PA13
    BSP_IO_PORTA_PIN_14 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 14U, ///< JTCK/SWCLK - PA14
    BSP_IO_PORTA_PIN_15 = (0U << BSP_IO_PORT_TYPE_SHIFT) | 15U, ///< JTDI - TIM2_CH1_ETR/PA15/SPI1_NSS

    BSP_IO_PORTB_PIN_0 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 0U, ///< ADC12_IN8/TIM3_CH3 - TIM1_CH2N
    BSP_IO_PORTB_PIN_1 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 1U, ///< ADC12_IN9/TIM3_CH4 - TIM1_CH3N
    BSP_IO_PORTB_PIN_2 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 2U, ///< PB2/BOOT1
    BSP_IO_PORTB_PIN_3 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 3U, ///< JTDO - TIM2_CH2/PB3/TRACESWO/SPI1_SCK
    BSP_IO_PORTB_PIN_4 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 4U, ///< JNTRST - TIM3_CH1/PB4/SPI1_MISO
    BSP_IO_PORTB_PIN_5 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 5U, ///< I2C1_SMBAl - TIM3_CH2/SPI1_MOSI
    BSP_IO_PORTB_PIN_6 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 6U, ///< I2C1_SCL/TIM4_CH1 - USART1_TX
    BSP_IO_PORTB_PIN_7 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 7U, ///< I2C1_SDA/TIM4_CH2 - USART1_RX
    BSP_IO_PORTB_PIN_8 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 8U, ///< TIM4_CH3 - I2C1_SCL/CANRX
    BSP_IO_PORTB_PIN_9 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 9U, ///< TIM4_CH4 - I2C1_SDA/CANTX
    BSP_IO_PORTB_PIN_10 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 10U, ///< I2C2_SCL/USART3_TX - TIM2_CH3
    BSP_IO_PORTB_PIN_11 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 11U, ///< I2C2_SDA/USART3_RX - TIM2_CH4
    BSP_IO_PORTB_PIN_12 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 12U, ///< SPI2_NSS/I2C2_SMBAl/USART3_CK/TIM1_BKIN
    BSP_IO_PORTB_PIN_13 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 13U, ///< SPI2_SCK/USART3_CTS/TIM1_CH1N
    BSP_IO_PORTB_PIN_14 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 14U, ///< SPI2_MISO/USART3_RTS/TIM1_CH2N
    BSP_IO_PORTB_PIN_15 = (1U << BSP_IO_PORT_TYPE_SHIFT) | 15U, ///< SPI2_MOSI/TIM1_CH3N

    BSP_IO_PORTC_PIN_13 = (2U << BSP_IO_PORT_TYPE_SHIFT) | 13U, ///< TAMPER-RTC
    BSP_IO_PORTC_PIN_14 = (2U << BSP_IO_PORT_TYPE_SHIFT) | 14U, ///< OSC32_IN
    BSP_IO_PORTC_PIN_15 = (2U << BSP_IO_PORT_TYPE_SHIFT) | 15U, ///< OSC32_OUT
} bsp_io_t;

#endif